import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import { unregister } from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

// Unregister service worker - no service-worker.js is generated by this CRA version,
// and stale/broken service workers can intercept routes and cause blank pages
unregister();
